force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/DateBooked__c.field-meta.xml
<CustomField>
    <fullName>DateBooked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>Unique auto-generated Exchange Trade Identifier</description>
    <inlineHelpText>Unique auto-generated Exchange Trade Identifier</inlineHelpText>
    <label>ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradesController.cls
/*
 *  Apex Controller for Trades List View component
 *  @author Paul Drozd
 *  @since 09-11-2020
 */
public with sharing class TradesController {

    @AuraEnabled(cacheable=true)
    public static List<Trade__c> getList(){
        return [SELECT Id, SellCurrency__c, SellAmount__c, BuyCurrency__c, 
                       BuyAmount__c, Rate__c, DateBooked__c
                FROM Trade__c WHERE ID__c != null ORDER BY DateBooked__c DESC];
    }

}