force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/DateBooked__c.field-meta.xml
<CustomField>
    <fullName>DateBooked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>Unique auto-generated Exchange Trade Identifier</description>
    <inlineHelpText>Unique auto-generated Exchange Trade Identifier</inlineHelpText>
    <label>ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/services/TradeService.cls
/*
 * Service class for Trade-related operations
 * 
 * @author Pavel Drozd
 * @since 09-11-2020
 */
public with sharing class TradeService {

    // TO DO: move to Custom Settings / Custom Metadata Types, so that Queue name can be quickly changed
    private static final String TRADE_REVIEWER_QUEUE = 'Trade reviewers';
    private static final String ID_PREFIX = 'TR';
    private static final Integer ID_POSTFIX_LENGTH = 7;
    private static String idPatternString = ID_PREFIX + '[A-Z0-9]{'+ ID_POSTFIX_LENGTH +'}';

    private List<Trade__c> trades = new List<Trade__c>();

    public TradeService(List<Trade__c> trades) {
        this.trades = trades;
    }

    /*
     *  Checks whether ID__c values are populated.
     *  Typically ID__c is popoulated by JS code, but this method
     *  is needed in case when a new Trade__c is created not via the
     *  Lightning web component.
     */
    public void populateIDs() {
        Pattern idPattern = Pattern.compile(idPatternString);
        Boolean matches = true;
        for (Trade__c trade: this.trades) {
            matches = true;
            if (String.isNotBlank(trade.ID__c)) {
                matches = idPattern.matcher(trade.ID__c).matches();
            }
            if (String.isBlank(trade.ID__c) || !matches) {
                trade.ID__c = ID_PREFIX + generateRandomString(ID_POSTFIX_LENGTH);
            }
        }
    }

    public void createChatterPosts() {
        Set<Id> usersToNotify;
        try {
            usersToNotify = QueueSelector.getQueueMemberIds(TRADE_REVIEWER_QUEUE);
        } catch (QueryException exc) {
            trades[0].addError('Please check your org configuration. We cannot find "' + TRADE_REVIEWER_QUEUE + '" queue.');
        }
        try {
            ChatterService chatter = new ChatterService();
            for (Trade__c trade: this.trades) {
                chatter.addPost(usersToNotify, this.getPostMessage(trade), trade.Id); 
            }
            chatter.send();
        } catch(CustomException exc) {
            trades[0].addError('Cannot create Chatter post: ' + exc.getMessage());
        }
    }

    private String getPostMessage(Trade__c trade) {
        List<Object> params = new List<Object>{
            trade.SellCurrency__c, trade.SellAmount__c, 
            trade.BuyCurrency__c, trade.BuyAmount__c,
            trade.Rate__c, trade.DateBooked__c,
            URL.getSalesforceBaseUrl().toExternalForm() + '/' + trade.Id 
        };
        return String.format(Label.NewTradePostMessage, params);
    } 

    private static String generateRandomString(Integer length) {
        Blob blobKey = Crypto.generateAesKey(128);
        return EncodingUtil.convertToHex(blobKey).substring(0,length).toUpperCase();
    }
}